module.exports = {
  // Socket.IO reserved events
  SOCKET_CONNECTED: 'connection',
  // saga mechanics events
  ACTION_INITIATED: 'ACTION/INITIATED',
  ACTION_SUCCEEDED: 'ACTION/SUCCEEDED',
  ACTION_FAILED: 'ACTION/FAILED',
  ACTION_ROLLBACK_INITIATED: 'ACTION/ROLLBACK_INITIATED',
  ACTION_ROLLBACK_SUCCEEDED: 'ACTION/ROLLBACK_SUCCEEDED',
  ACTION_ROLLBACK_FAILED: 'ACTION/ROLLBACK_FAILED',
};
