const { EVENTS } = require('@aqueoss/system');

module.exports = {
  ...EVENTS,
  ACCOUNTS_MASS_CREATION_REQUESTED: 'ACCOUNTS/MASS_CREATION_REQUESTED',
  ACCOUNTS_MASS_CREATED: 'ACCOUNTS/MASS_CREATED',
  ACCOUNTS_MASS_CREATE_FAILED: 'ACCOUNTS/MASS_CREATE_FAILED',
};
