const { EVENTS } = require('@aqueoss/system');

module.exports = {
  ...EVENTS,
  // client incoming events
  FROM_CLIENT_ACCOUNTS_CREATION_REQUESTED: 'FROM_CLIENT/ACCOUNTS_CREATION_REQUESTED',
  // client outgoing events
  TO_CLIENT_ACCOUNTS_CREATED: 'TO_CLIENT/ACCOUNTS_CREATED',
  TO_CLIENT_ACCOUNTS_CREATE_FAILED: 'TO_CLIENT/ACCOUNTS_CREATE_FAILED',
  STATE_CHANGE_ACCOUNTS_CREATED: 'STATE_CHANGE/ACCOUNTS_CREATED'
};
