module.exports = {
  // Socket.IO reserved events
  SOCKET_CONNECTED: 'connection',
  // client incoming events
  ACCOUNTS_CREATION_REQUESTED_BY_CLIENT: 'CLIENT/ACCOUNTS_CREATION_REQUESTED',
  // saga mechanics events
  ACTION_INITIATED: 'ACTION/INITIATED',
  ACTION_SUCCEEDED: 'ACTION/SUCCEEDED',
  ACTION_FAILED: 'ACTION/FAILED',
  ACTION_ROLLBACK_INITIATED: 'ACTION/ROLLBACK_INITIATED',
  ACTION_ROLLBACK_SUCCEEDED: 'ACTION/ROLLBACK_SUCCEEDED',
  ACTION_ROLLBACK_FAILED: 'ACTION/ROLLBACK_FAILED',
  STATE_CHANGE_ACCOUNTS_CREATED: 'STATE_CHANGE/ACCOUNTS_CREATED'
};
