module.exports = {
  // Socket.IO reserved events
  SOCKET_CONNECTED: 'connection',
  // client incoming events
  ACCOUNTS_CREATION_REQUESTED_BY_CLIENT: 'EVENT/CLIENT/ACCOUNTS_CREATION_REQUESTED',
  // saga mechanics events
  SAGA_INITIATED: 'EVENT/SAGA/INITIATED',
  SAGA_SUCCEEDED: 'EVENT/SAGA/SUCCEEDED',
  SAGA_FAILED: 'EVENT/SAGA/FAILED',
  SAGA_ROLLBACK_INITIATED: 'EVENT/SAGA/ROLLBACK_INITIATED',
  SAGA_ROLLBACK_SUCCEEDED: 'EVENT/SAGA/ROLLBACK_SUCCEEDED',
  SAGA_ROLLBACK_FAILED: 'EVENT/SAGA/ROLLBACK_FAILED',
};
